package net.mc_pandacraft.java.plugin.pandacraftutils.commands;

import net.mc_pandacraft.java.plugin.pandacraftutils.players.OnlinePlayer;
import net.mc_pandacraft.java.plugin.pandacraftutils.players.OnlinePlayerManager;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class CommandCoeur extends AbstractCommandExecutor {
	
	public CommandCoeur() {
		super("coeur");
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label,
			String[] args) {
		
		if (!(sender instanceof Player)) {
			sender.sendMessage(ChatColor.RED+"seul un joueur en ligne peut effectuer cette commande");
			return true;
		}

		Player p = (Player) sender;
		OnlinePlayer op = OnlinePlayerManager.get(p);
		
		boolean heartEnabled = op.toggleHeartThrow();
		
		if (heartEnabled)
			p.sendMessage(ChatColor.GREEN+"Activation des coeurs (au dessus de votre tête)");
		else
			p.sendMessage(ChatColor.GREEN+"Désactivation des coeurs");
		
		if (heartEnabled && op.isVanished()) {
			p.sendMessage(ChatColor.GOLD+"Attention : vous êtes vanish, mais les coeurs sont quand même visible pour les autres joueurs");
		}
		
		
		return true;
	}

}
