package net.mc_pandacraft.java.plugin.pandacraftutils.commands;

import net.mc_pandacraft.java.plugin.pandacraftutils.players.OnlinePlayer;
import net.mc_pandacraft.java.plugin.pandacraftutils.players.OnlinePlayerManager;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

public class CommandCoeur extends AbstractCommandExecutor {
	
	public CommandCoeur() {
		super("coeur");
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String label,
			String[] args) {
		
		if (!(sender instanceof Player)) {
			sender.sendMessage(ChatColor.RED+"seul un joueur en ligne peut effectuer cette commande");
			return true;
		}

		Player p = (Player) sender;
		OnlinePlayer op = OnlinePlayerManager.get(p);
		
		boolean heartEnabled = op.toggleHeartThrow();
		
		if (heartEnabled)
			p.sendMessage(ChatColor.GREEN+"Activation des coeurs (au dessus de votre tête)");
		else
			p.sendMessage(ChatColor.GREEN+"Désactivation des coeurs");
		
		if (heartEnabled && op.isVanished()) {
			p.sendMessage(ChatColor.GOLD+"Attention : vous êtes vanish, mais les coeurs sont quand même visible pour les autres joueurs");
		}
		
		// cadeau spécial pour MissElwing
		// TODO effacer du code après qu'elle l'aie vue une fois
		if (heartEnabled && (p.getName().equals("MissElwing") || p.getName().equals("marcbal"))) {
			String[] messages = {
					ChatColor.GREEN+"",
					ChatColor.GREEN+"♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥",
					ChatColor.GREEN+"Coucou ma chérie <3 J'ai fait ce petit message rien que pour toi (personne d'autre peut le lire)", // sauf les devs qui auront accès au github x)
					ChatColor.GREEN+"On dit que la St-Valentin est une fête commerciale, mais est-ce vraiment nécessaire de dépenser de l'argent pour prouver notre amour ?",
					ChatColor.GREEN+"Moi, c'est autre chose que je dépense pour toi : c'est du temps et de l'énergie, et c'est presque gratuit :3 et en plus, je prends plaisir à ça :D",
					ChatColor.GREEN+"J'ai pensé à toi en créant la commande /"+label+", permettant à un joueur de lancer des coeurs à volonté (tu sais, on a vu ça sur Mineplex ;) )",
					ChatColor.GREEN+"En tout cas, sache que je t'aime fort fort fort, et j'espère que ce petit message à ton attention te fais plaisir :)",
					ChatColor.GREEN+"                                 (signé Marc, ton chéri d'amour)",
					ChatColor.GREEN+"♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥♥",
			};
			
			p.sendMessage(messages);
		}
		
		
		return true;
	}

}
