package net.mc_pandacraft.java.plugin.pandacraftutils.simple_commands.speed_message;

import java.util.ArrayList;
import java.util.List;

import net.mc_pandacraft.java.plugin.pandacraftutils.PandacraftUtils;

import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;

public class CommandSpeedMessage implements CommandExecutor {

	
	private PandacraftUtils plugin;
	private List<Message> messages = new ArrayList<Message>();
	
	public CommandSpeedMessage(PandacraftUtils pl)
	{
		plugin = pl;
		
        plugin.getCommand("speedmessage").setExecutor(this);
        
        

        messages.add(new Message("site", "Site internet du serveur : http://www.mc-pandacraft.net/", "pandacraft.grade.all"));
        messages.add(new Message("inscription", "Page d'inscription : http://mc-pandacraft.net/?p=inscription", "pandacraft.grade.default"));
        messages.add(new Message("ultimate", "Grade [Ultimate] : http://www.mc-pandacraft.net/?p=ultimate", "pandacraft.grade.not_default"));
        messages.add(new Message("help", "Si vous avez besoin d'aides pour les commandes, faites &7/help", "pandacraft.grade.all"));
        
        
	}

	@Override
	public boolean onCommand(CommandSender sender, Command cmd, String alias,
			String[] args) {
		
		// TODO voir le plugin.yml pour l'utilisation de la commande
		
		return false;
	}

}
